name: YaSpeller All

on:
  push:
    branches:
      - main

jobs:
  yaspeller:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Проверка правописания в main
        run: |
          npm i -g yaspeller
          yaspeller --only-errors *
